# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jameswlane
open_collective: # Replace with a single Open Collective username
ko_fi: jameswlane
tidelift: # npm/react-pure-loaders
paypal: https://www.paypal.me/jameswlane
# buymeacoffee: https://buymeacoff.ee/jameswlane
# tippinme: https://tippin.me/@jameswlane
